# Generated by Django 2.1 on 2021-02-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210228_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
    ]
