# Generated by Django 2.1 on 2021-02-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210228_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
    ]
