# Generated by Django 2.1 on 2021-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210228_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
